CREATE TABLE IF NOT EXISTS "cooking_category" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cooking_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "cooking_recipe_category" (
	"recipe_id" integer NOT NULL,
	"category_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "cooking_recipe_category_recipe_id_category_id_pk" PRIMARY KEY("recipe_id","category_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "cooking_recipe" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cooking_recipe_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256) NOT NULL,
	"description" text,
	"ingredients" jsonb NOT NULL,
	"instructions" text NOT NULL,
	"prep_time" integer,
	"cook_time" integer,
	"servings" integer,
	"image_url" varchar(256),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	"user_id" varchar(256) NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "cooking_recipe_category" ADD CONSTRAINT "cooking_recipe_category_recipe_id_cooking_recipe_id_fk" FOREIGN KEY ("recipe_id") REFERENCES "public"."cooking_recipe"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "cooking_recipe_category" ADD CONSTRAINT "cooking_recipe_category_category_id_cooking_category_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."cooking_category"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "title_idx" ON "cooking_recipe" USING btree ("title");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_id_idx" ON "cooking_recipe" USING btree ("user_id");